// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-lesson.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("A Supabase publishable/anon key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Not authenticated");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new Error("Not authenticated. Please connect your account first.");
  }
  return ctx.getUserId();
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: data
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/get-lesson.ts
var get_lesson_default = defineTool({
  name: "get_lesson",
  title: "Get lesson content",
  description: "Fetch a lesson's full content by slug: intro, learning outcomes, AI tips, ordered content sections and linked vocabulary items.",
  inputSchema: {
    slug: z.string().describe("Lesson slug, e.g. a0-m1-l1.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data: lesson, error } = await supabase.from("lessons").select(
        "id, slug, title_en, title_ar, description_ar, intro_en, intro_ar, learning_outcomes_ar, ai_tips_ar, cefr_level, duration_min"
      ).eq("slug", slug).maybeSingle();
      if (error) return fail(error.message);
      if (!lesson) return fail(`No lesson found with slug "${slug}".`);
      const [sections, vocab] = await Promise.all([
        supabase.from("lesson_sections").select("section_type, title_en, title_ar, content, order_index").eq("lesson_id", lesson.id).order("order_index"),
        supabase.from("lesson_vocabulary").select("order_index, vocabulary_items(word_en, phonetic, meaning_ar, example_en, example_ar)").eq("lesson_id", lesson.id).order("order_index")
      ]);
      if (sections.error) return fail(sections.error.message);
      if (vocab.error) return fail(vocab.error.message);
      return ok({
        lesson,
        sections: sections.data ?? [],
        vocabulary: (vocab.data ?? []).map((v) => v.vocabulary_items)
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_progress_default = defineTool2({
  name: "get_my_progress",
  title: "Get my learning progress",
  description: "Get the signed-in learner's own progress: CEFR level, points, streak, placement results and recent quiz scores.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const [profile, scores] = await Promise.all([
        supabase.from("profiles").select(
          "display_name, cefr_level, current_level, total_points, streak_days, completed_lessons, placement_completed, placement_score, placement_strengths, placement_weaknesses"
        ).eq("id", userId).maybeSingle(),
        supabase.from("quiz_scores").select("lesson_id, score, total, completed_at").eq("user_id", userId).order("completed_at", { ascending: false }).limit(20)
      ]);
      if (profile.error) return fail(profile.error.message);
      if (scores.error) return fail(scores.error.message);
      return ok({ profile: profile.data, recent_quiz_scores: scores.data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/tools/list-lessons.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_lessons_default = defineTool3({
  name: "list_lessons",
  title: "List lessons",
  description: "List published lessons. Optionally filter by module slug (e.g. a0-m1-alphabet-sounds). Archived legacy lessons are excluded.",
  inputSchema: {
    module_slug: z2.string().optional().describe("Slug of the module to list lessons for."),
    limit: z2.number().int().optional().describe("Max lessons to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ module_slug, limit }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      let moduleId;
      if (module_slug) {
        const { data: mod, error: modErr } = await supabase.from("modules").select("id").eq("slug", module_slug).maybeSingle();
        if (modErr) return fail(modErr.message);
        if (!mod) return fail(`No module found with slug "${module_slug}".`);
        moduleId = mod.id;
      }
      let query = supabase.from("lessons").select("id, slug, title_en, title_ar, description_ar, cefr_level, duration_min, order_index, module_id").eq("is_published", true).is("archived_at", null).order("order_index").limit(Math.min(limit ?? 50, 200));
      if (moduleId) query = query.eq("module_id", moduleId);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({ lessons: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/tools/list-modules.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_modules_default = defineTool4({
  name: "list_modules",
  title: "List curriculum modules",
  description: "List the published curriculum modules of the English learning platform, with CEFR level, Arabic/English titles and estimated hours.",
  inputSchema: {
    level_code: z3.string().optional().describe("Optional CEFR level filter, e.g. A0, A1, B1.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ level_code }, ctx) => {
    try {
      requireAuth(ctx);
      let query = supabaseForUser(ctx).from("modules").select("id, slug, level_code, title_en, title_ar, description_ar, est_hours, order_index").eq("is_published", true).order("order_index");
      if (level_code) query = query.eq("level_code", level_code.toUpperCase());
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({ modules: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/tools/list-my-vocabulary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_vocabulary_default = defineTool5({
  name: "list_my_vocabulary",
  title: "List my saved vocabulary",
  description: "List the words the signed-in learner has saved to their personal vocabulary list.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const { data, error } = await supabaseForUser(ctx).from("user_vocabulary").select("saved_at, dictionary_words(word, phonetic, meaning_ar, example_en, example_ar, cefr_level)").eq("user_id", userId).order("saved_at", { ascending: false });
      if (error) return fail(error.message);
      return ok({
        saved_words: (data ?? []).map((row) => ({ saved_at: row.saved_at, ...row.dictionary_words ?? {} }))
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/tools/save-word.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var save_word_default = defineTool6({
  name: "save_word",
  title: "Save a word to my vocabulary",
  description: "Save a dictionary word to the signed-in learner's personal vocabulary list. The word must already exist in the app dictionary.",
  inputSchema: {
    word: z4.string().describe("The exact English word to save, e.g. 'library'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ word }, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const term = word.trim();
      if (!term) return fail("Word cannot be empty.");
      const { data: entry, error: lookupError } = await supabase.from("dictionary_words").select("id, word").ilike("word", term).maybeSingle();
      if (lookupError) return fail(lookupError.message);
      if (!entry) return fail(`"${term}" is not in the dictionary yet.`);
      const { error } = await supabase.from("user_vocabulary").upsert({ user_id: userId, word_id: entry.id }, { onConflict: "user_id,word_id" });
      if (error) return fail(error.message);
      return ok({ saved: true, word: entry.word });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/tools/search-dictionary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var search_dictionary_default = defineTool7({
  name: "search_dictionary",
  title: "Search the English-Arabic dictionary",
  description: "Search the app's English-Arabic learning dictionary for a word and return phonetics, Arabic meaning and example sentences.",
  inputSchema: {
    query: z5.string().describe("English word or partial word to look up.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    try {
      requireAuth(ctx);
      const term = query.trim();
      if (!term) return fail("Query cannot be empty.");
      const { data, error } = await supabaseForUser(ctx).from("dictionary_words").select("id, word, phonetic, meaning_ar, example_en, example_ar, cefr_level").ilike("word", `%${term}%`).order("word").limit(20);
      if (error) return fail(error.message);
      return ok({ results: data ?? [] });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unexpected error");
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "oxsskdiqkxjuvjhdydvy";
var mcp_default = defineMcp({
  name: "daw-albayt-mcp",
  title: "\u0636\u0648\u0621 \u0627\u0644\u0628\u064A\u062A \u2014 English Learning",
  version: "0.1.0",
  instructions: "Tools for the \u0636\u0648\u0621 \u0627\u0644\u0628\u064A\u062A Arabic-first English learning platform. Use `list_modules` and `list_lessons` to browse the CEFR curriculum, `get_lesson` for full lesson content (sections + vocabulary), `search_dictionary` for English-Arabic word lookups, `save_word` to add a word to the learner's vocabulary list, `list_my_vocabulary` to review saved words, and `get_my_progress` for the signed-in learner's level, points, streak and quiz scores. All tools act as the signed-in learner only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_modules_default,
    list_lessons_default,
    get_lesson_default,
    search_dictionary_default,
    save_word_default,
    list_my_vocabulary_default,
    get_my_progress_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
